# Generated by Django 5.2 on 2025-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("large_images", models.TextField(default="")),
                ("small_images", models.TextField(default="")),
                ("director", models.CharField(default="", max_length=255)),
                ("actors", models.TextField(default="")),
                ("countries", models.CharField(default="", max_length=1000)),
                ("aka", models.CharField(default="", max_length=1000)),
                ("tags", models.CharField(default="", max_length=1000)),
                ("language", models.CharField(default="", max_length=100)),
                ("durations", models.TextField(default="")),
                ("pubdate", models.CharField(default="", max_length=1000)),
                ("rating", models.FloatField()),
                ("summary", models.TextField(default="")),
                ("like_count", models.IntegerField()),
            ],
        ),
    ]
