# Generated by Django 5.2 on 2025-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectMovieDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(unique=True, verbose_name="电影ID")),
                (
                    "original_title",
                    models.CharField(
                        default="", max_length=1000, verbose_name="原始标题"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=1000, verbose_name="中文标题"
                    ),
                ),
                ("rating", models.TextField(default="", verbose_name="评分")),
                (
                    "ratings_count",
                    models.IntegerField(default=0, verbose_name="评分数"),
                ),
                (
                    "pubdate",
                    models.CharField(
                        default="", max_length=1000, verbose_name="上映日期"
                    ),
                ),
                (
                    "pubdates",
                    models.CharField(
                        default="", max_length=1000, verbose_name="上映日期2"
                    ),
                ),
                ("year", models.IntegerField(default=0, verbose_name="年份")),
                (
                    "countries",
                    models.CharField(
                        default="", max_length=1000, verbose_name="制片国家/地区"
                    ),
                ),
                (
                    "mainland_pubdate",
                    models.CharField(
                        default="", max_length=1000, verbose_name="主要上映日期"
                    ),
                ),
                (
                    "aka",
                    models.CharField(default="", max_length=1000, verbose_name="又名"),
                ),
                (
                    "tags",
                    models.CharField(default="", max_length=1000, verbose_name="标签"),
                ),
                ("durations", models.TextField(default="", verbose_name="时长")),
                (
                    "genres",
                    models.CharField(default="", max_length=1000, verbose_name="类型"),
                ),
                ("videos", models.TextField(default="", verbose_name="短视频")),
                ("wish_count", models.IntegerField(default=0, verbose_name="想看")),
                (
                    "reviews_count",
                    models.IntegerField(default=0, verbose_name="短评数"),
                ),
                (
                    "comments_count",
                    models.IntegerField(default=0, verbose_name="评论数"),
                ),
                ("collect_count", models.IntegerField(default=0, verbose_name="收藏")),
                ("images", models.TextField(default="", verbose_name="封面图片")),
                ("photos", models.TextField(default="", verbose_name="照片")),
                (
                    "languages",
                    models.CharField(default="", max_length=1000, verbose_name="语言"),
                ),
                ("writers", models.TextField(default="", verbose_name="作者")),
                ("actor", models.TextField(default="", verbose_name="演员")),
                ("summary", models.TextField(default="", verbose_name="简介")),
                ("directors", models.TextField(default="", verbose_name="导演")),
                (
                    "record_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
            ],
            options={
                "verbose_name": "电影详情数据",
                "verbose_name_plural": "电影详情数据",
            },
        ),
        migrations.CreateModel(
            name="CollectMovieTypeDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_type",
                    models.CharField(
                        default="", max_length=100, unique=True, verbose_name="电影类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影类型表",
                "verbose_name_plural": "电影类型表",
            },
        ),
    ]
